### ISSUE TITLE
Tasks not appearing 

### ISSUE THREAD

**Issue by andremichi** [jgauth/MMM-GoogleTasks#3]
I installed today the module and it's not displaying any task from the lists. Just got this JS exception:

```Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Class.getDom (MMM-GoogleTasks.js:87)
    at main.js:110
    at new Promise (<anonymous>)
    at updateDom (main.js:109)
    at main.js:53
    at Array.forEach (<anonymous>)
    at createDomObjects (main.js:24)
    at Object.modulesStarted (main.js:471)
    at startModules (loader.js:59)```

Code:
```		 var numTasks = Object.keys(this.tasks).length;

```
I'm not JS expert, or begginer. But it's not returning anything. =)

**Comment by jayked** [comment]
Possible fix available in #5

**Comment by imorenocif** [comment]
How i can see the exception, mi module don't show any task, but I have the correct ID and the api activated

**Comment by jayked** [comment]
@imorenocif As you can see in my earlier comment you can possibly find the fix in #5

**Comment by RickSanchezC136** [comment]
Having the same problem. 
Fresh install, no other modules installed.
Been trying to get this module working for over 4 hours now. really disappointed as I actually really need this in order to maintain an acceptable quality of life...

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Class.getDom (MMM-GoogleTasks.js:87:26)
    at main.js:113:35
    at new Promise (<anonymous>)
    at updateDom (main.js:111:10)
    at main.js:53:31
    at Array.forEach (<anonymous>)
    at createDomObjects (main.js:20:11)
    at Object.modulesStarted (main.js:504:4)
    at startModules (loader.js:55:6)

MMM-GoogleTasks.js:87 
        
       Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Class.getDom (MMM-GoogleTasks.js:87:26)
    at main.js:113:35
    at new Promise (<anonymous>)
    at updateDom (main.js:111:10)
    at main.js:53:31
    at Array.forEach (<anonymous>)
    at createDomObjects (main.js:20:11)
    at Object.modulesStarted (main.js:504:4)
    at startModules (loader.js:55:6)
